// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment.proto

package comment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommentStory struct {
	Commentdata          []*CommentData `protobuf:"bytes,1,rep,name=commentdata" json:"commentdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommentStory) Reset()         { *m = CommentStory{} }
func (m *CommentStory) String() string { return proto.CompactTextString(m) }
func (*CommentStory) ProtoMessage()    {}
func (*CommentStory) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{0}
}

func (m *CommentStory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentStory.Unmarshal(m, b)
}
func (m *CommentStory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentStory.Marshal(b, m, deterministic)
}
func (m *CommentStory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentStory.Merge(m, src)
}
func (m *CommentStory) XXX_Size() int {
	return xxx_messageInfo_CommentStory.Size(m)
}
func (m *CommentStory) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentStory.DiscardUnknown(m)
}

var xxx_messageInfo_CommentStory proto.InternalMessageInfo

func (m *CommentStory) GetCommentdata() []*CommentData {
	if m != nil {
		return m.Commentdata
	}
	return nil
}

type CommentData struct {
	UserName             *string  `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	AnswerName           *string  `protobuf:"bytes,2,opt,name=answerName" json:"answerName,omitempty"`
	Time                 *string  `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
	Content              *string  `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentData) Reset()         { *m = CommentData{} }
func (m *CommentData) String() string { return proto.CompactTextString(m) }
func (*CommentData) ProtoMessage()    {}
func (*CommentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{1}
}

func (m *CommentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentData.Unmarshal(m, b)
}
func (m *CommentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentData.Marshal(b, m, deterministic)
}
func (m *CommentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentData.Merge(m, src)
}
func (m *CommentData) XXX_Size() int {
	return xxx_messageInfo_CommentData.Size(m)
}
func (m *CommentData) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentData.DiscardUnknown(m)
}

var xxx_messageInfo_CommentData proto.InternalMessageInfo

func (m *CommentData) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *CommentData) GetAnswerName() string {
	if m != nil && m.AnswerName != nil {
		return *m.AnswerName
	}
	return ""
}

func (m *CommentData) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

func (m *CommentData) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*CommentStory)(nil), "comment.CommentStory")
	proto.RegisterType((*CommentData)(nil), "comment.CommentData")
}

func init() { proto.RegisterFile("comment.proto", fileDescriptor_749aee09ea917828) }

var fileDescriptor_749aee09ea917828 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xdc, 0xb8,
	0x78, 0x9c, 0x21, 0xcc, 0xe0, 0x92, 0xfc, 0xa2, 0x4a, 0x21, 0x33, 0x2e, 0x6e, 0xa8, 0x54, 0x4a,
	0x62, 0x49, 0xa2, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0x4c, 0x37, 0x54, 0xad,
	0x4b, 0x62, 0x49, 0x62, 0x10, 0xb2, 0x42, 0xa5, 0x72, 0x2e, 0x6e, 0x24, 0x39, 0x21, 0x29, 0x2e,
	0x8e, 0xd2, 0xe2, 0xd4, 0x22, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x38, 0x5f, 0x48, 0x8e, 0x8b, 0x2b, 0x31, 0xaf, 0xb8, 0x1c, 0x2a, 0xcb, 0x04, 0x96, 0x45, 0x12,
	0x11, 0x12, 0xe2, 0x62, 0x29, 0xc9, 0xcc, 0x4d, 0x95, 0x60, 0x06, 0xcb, 0x80, 0xd9, 0x42, 0x12,
	0x5c, 0xec, 0xc9, 0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x12, 0x2c, 0x60, 0x61, 0x18, 0x17, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x8f, 0xdd, 0x87, 0x37, 0xd9, 0x00, 0x00, 0x00,
}
