// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package store

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommentStory struct {
	Commentdata          []*CommentData `protobuf:"bytes,1,rep,name=commentdata" json:"commentdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommentStory) Reset()         { *m = CommentStory{} }
func (m *CommentStory) String() string { return proto.CompactTextString(m) }
func (*CommentStory) ProtoMessage()    {}
func (*CommentStory) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *CommentStory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentStory.Unmarshal(m, b)
}
func (m *CommentStory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentStory.Marshal(b, m, deterministic)
}
func (m *CommentStory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentStory.Merge(m, src)
}
func (m *CommentStory) XXX_Size() int {
	return xxx_messageInfo_CommentStory.Size(m)
}
func (m *CommentStory) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentStory.DiscardUnknown(m)
}

var xxx_messageInfo_CommentStory proto.InternalMessageInfo

func (m *CommentStory) GetCommentdata() []*CommentData {
	if m != nil {
		return m.Commentdata
	}
	return nil
}

type CommentData struct {
	UserName             *string  `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	Answer               *string  `protobuf:"bytes,2,opt,name=answer" json:"answer,omitempty"`
	Time                 *string  `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
	Content              *string  `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	Id                   *int32   `protobuf:"varint,5,opt,name=id" json:"id,omitempty"`
	IsDel                *bool    `protobuf:"varint,6,opt,name=isDel" json:"isDel,omitempty"`
	Praise               *uint32  `protobuf:"fixed32,7,opt,name=praise" json:"praise,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentData) Reset()         { *m = CommentData{} }
func (m *CommentData) String() string { return proto.CompactTextString(m) }
func (*CommentData) ProtoMessage()    {}
func (*CommentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *CommentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentData.Unmarshal(m, b)
}
func (m *CommentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentData.Marshal(b, m, deterministic)
}
func (m *CommentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentData.Merge(m, src)
}
func (m *CommentData) XXX_Size() int {
	return xxx_messageInfo_CommentData.Size(m)
}
func (m *CommentData) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentData.DiscardUnknown(m)
}

var xxx_messageInfo_CommentData proto.InternalMessageInfo

func (m *CommentData) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *CommentData) GetAnswer() string {
	if m != nil && m.Answer != nil {
		return *m.Answer
	}
	return ""
}

func (m *CommentData) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

func (m *CommentData) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *CommentData) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CommentData) GetIsDel() bool {
	if m != nil && m.IsDel != nil {
		return *m.IsDel
	}
	return false
}

func (m *CommentData) GetPraise() uint32 {
	if m != nil && m.Praise != nil {
		return *m.Praise
	}
	return 0
}

type UserTopics struct {
	Usertopicdata        []*UserTopicData `protobuf:"bytes,1,rep,name=usertopicdata" json:"usertopicdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserTopics) Reset()         { *m = UserTopics{} }
func (m *UserTopics) String() string { return proto.CompactTextString(m) }
func (*UserTopics) ProtoMessage()    {}
func (*UserTopics) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *UserTopics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTopics.Unmarshal(m, b)
}
func (m *UserTopics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTopics.Marshal(b, m, deterministic)
}
func (m *UserTopics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTopics.Merge(m, src)
}
func (m *UserTopics) XXX_Size() int {
	return xxx_messageInfo_UserTopics.Size(m)
}
func (m *UserTopics) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTopics.DiscardUnknown(m)
}

var xxx_messageInfo_UserTopics proto.InternalMessageInfo

func (m *UserTopics) GetUsertopicdata() []*UserTopicData {
	if m != nil {
		return m.Usertopicdata
	}
	return nil
}

type UserTopicData struct {
	Sid                  *int32   `protobuf:"varint,1,opt,name=sid" json:"sid,omitempty"`
	Aid                  *int32   `protobuf:"varint,2,opt,name=aid" json:"aid,omitempty"`
	Time                 *string  `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
	Title                *string  `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTopicData) Reset()         { *m = UserTopicData{} }
func (m *UserTopicData) String() string { return proto.CompactTextString(m) }
func (*UserTopicData) ProtoMessage()    {}
func (*UserTopicData) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{3}
}

func (m *UserTopicData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTopicData.Unmarshal(m, b)
}
func (m *UserTopicData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTopicData.Marshal(b, m, deterministic)
}
func (m *UserTopicData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTopicData.Merge(m, src)
}
func (m *UserTopicData) XXX_Size() int {
	return xxx_messageInfo_UserTopicData.Size(m)
}
func (m *UserTopicData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTopicData.DiscardUnknown(m)
}

var xxx_messageInfo_UserTopicData proto.InternalMessageInfo

func (m *UserTopicData) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *UserTopicData) GetAid() int32 {
	if m != nil && m.Aid != nil {
		return *m.Aid
	}
	return 0
}

func (m *UserTopicData) GetTime() string {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return ""
}

func (m *UserTopicData) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

type UserComments struct {
	Usercommentdata      []*UserCommentData `protobuf:"bytes,1,rep,name=usercommentdata" json:"usercommentdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UserComments) Reset()         { *m = UserComments{} }
func (m *UserComments) String() string { return proto.CompactTextString(m) }
func (*UserComments) ProtoMessage()    {}
func (*UserComments) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{4}
}

func (m *UserComments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserComments.Unmarshal(m, b)
}
func (m *UserComments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserComments.Marshal(b, m, deterministic)
}
func (m *UserComments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserComments.Merge(m, src)
}
func (m *UserComments) XXX_Size() int {
	return xxx_messageInfo_UserComments.Size(m)
}
func (m *UserComments) XXX_DiscardUnknown() {
	xxx_messageInfo_UserComments.DiscardUnknown(m)
}

var xxx_messageInfo_UserComments proto.InternalMessageInfo

func (m *UserComments) GetUsercommentdata() []*UserCommentData {
	if m != nil {
		return m.Usercommentdata
	}
	return nil
}

type UserCommentData struct {
	SubId                *int32       `protobuf:"varint,1,opt,name=subId" json:"subId,omitempty"`
	Aid                  *int32       `protobuf:"varint,2,opt,name=aid" json:"aid,omitempty"`
	Commentdata          *CommentData `protobuf:"bytes,3,opt,name=commentdata" json:"commentdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserCommentData) Reset()         { *m = UserCommentData{} }
func (m *UserCommentData) String() string { return proto.CompactTextString(m) }
func (*UserCommentData) ProtoMessage()    {}
func (*UserCommentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{5}
}

func (m *UserCommentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCommentData.Unmarshal(m, b)
}
func (m *UserCommentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCommentData.Marshal(b, m, deterministic)
}
func (m *UserCommentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCommentData.Merge(m, src)
}
func (m *UserCommentData) XXX_Size() int {
	return xxx_messageInfo_UserCommentData.Size(m)
}
func (m *UserCommentData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCommentData.DiscardUnknown(m)
}

var xxx_messageInfo_UserCommentData proto.InternalMessageInfo

func (m *UserCommentData) GetSubId() int32 {
	if m != nil && m.SubId != nil {
		return *m.SubId
	}
	return 0
}

func (m *UserCommentData) GetAid() int32 {
	if m != nil && m.Aid != nil {
		return *m.Aid
	}
	return 0
}

func (m *UserCommentData) GetCommentdata() *CommentData {
	if m != nil {
		return m.Commentdata
	}
	return nil
}

func init() {
	proto.RegisterType((*CommentStory)(nil), "store.CommentStory")
	proto.RegisterType((*CommentData)(nil), "store.CommentData")
	proto.RegisterType((*UserTopics)(nil), "store.UserTopics")
	proto.RegisterType((*UserTopicData)(nil), "store.UserTopicData")
	proto.RegisterType((*UserComments)(nil), "store.UserComments")
	proto.RegisterType((*UserCommentData)(nil), "store.UserCommentData")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xb6, 0x6e, 0xcb, 0xa5, 0xa5, 0xe8, 0x54, 0x55, 0x16, 0x53, 0x94, 0x29, 0x53,
	0x07, 0xc4, 0xc4, 0x84, 0x44, 0x07, 0x58, 0x10, 0x32, 0x30, 0x32, 0x98, 0xc6, 0x83, 0xa5, 0x26,
	0xae, 0xec, 0xab, 0x10, 0x3f, 0x8a, 0xff, 0x88, 0xec, 0xb8, 0x55, 0x5a, 0x2a, 0xb1, 0xdd, 0x77,
	0xf7, 0x92, 0x7b, 0xcf, 0x36, 0x64, 0x9e, 0xac, 0xd3, 0xcb, 0xad, 0xb3, 0x64, 0x91, 0x47, 0x28,
	0x56, 0x30, 0x79, 0xb0, 0x75, 0xad, 0x1b, 0x7a, 0x25, 0xeb, 0xbe, 0xf1, 0x16, 0xb2, 0x75, 0xcb,
	0x95, 0x22, 0x25, 0x58, 0xde, 0x2f, 0xb3, 0x1b, 0x5c, 0xb6, 0x5f, 0x26, 0xe5, 0x4a, 0x91, 0x92,
	0x5d, 0x59, 0xf1, 0xc3, 0x20, 0xeb, 0x0c, 0xf1, 0x1a, 0xc6, 0x3b, 0xaf, 0xdd, 0xb3, 0xaa, 0xb5,
	0x60, 0x39, 0x2b, 0x2f, 0xe4, 0x81, 0x71, 0x01, 0x43, 0xd5, 0xf8, 0x2f, 0xed, 0x44, 0x2f, 0x4e,
	0x12, 0x21, 0xc2, 0x80, 0x4c, 0xad, 0x45, 0x3f, 0x76, 0x63, 0x8d, 0x02, 0x46, 0x6b, 0xdb, 0x90,
	0x6e, 0x48, 0x0c, 0x62, 0x7b, 0x8f, 0x78, 0x09, 0x3d, 0x53, 0x09, 0x9e, 0xb3, 0x92, 0xcb, 0x9e,
	0xa9, 0x70, 0x0e, 0xdc, 0xf8, 0x95, 0xde, 0x88, 0x61, 0xce, 0xca, 0xb1, 0x6c, 0x21, 0xec, 0xda,
	0x3a, 0x65, 0xbc, 0x16, 0xa3, 0x9c, 0x95, 0x23, 0x99, 0xa8, 0x78, 0x04, 0x78, 0xf7, 0xda, 0xbd,
	0xd9, 0xad, 0x59, 0x7b, 0xbc, 0x83, 0x69, 0x70, 0x47, 0x81, 0x3a, 0xa9, 0xe7, 0x29, 0xf5, 0x41,
	0x19, 0x73, 0x1f, 0x4b, 0x8b, 0x0f, 0x98, 0x1e, 0xcd, 0xf1, 0x0a, 0xfa, 0xde, 0x54, 0x31, 0x35,
	0x97, 0xa1, 0x0c, 0x1d, 0x65, 0xaa, 0x98, 0x96, 0xcb, 0x50, 0x9e, 0x8d, 0x3a, 0x07, 0x4e, 0x86,
	0x36, 0x3a, 0x05, 0x6d, 0xa1, 0x78, 0x81, 0x49, 0xf8, 0x7d, 0x3a, 0x5b, 0x8f, 0xf7, 0x30, 0x0b,
	0xfb, 0xff, 0x5e, 0xd1, 0xa2, 0x63, 0xb6, 0x7b, 0x4d, 0xa7, 0xf2, 0xc2, 0xc2, 0xec, 0x44, 0x13,
	0x56, 0xfb, 0xdd, 0xe7, 0xd3, 0xde, 0x74, 0x0b, 0x67, 0x6c, 0x9f, 0xbc, 0x8d, 0xe0, 0xfe, 0xff,
	0xb7, 0xf1, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x24, 0x09, 0x5d, 0x66, 0x76, 0x02, 0x00, 0x00,
}
